apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: train-schedule
  name: train-schedule-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: train-schedule
#      tier: backend
  template: 
    metadata: 
      labels: 
        app: train-schedule
#        tier: backend
    spec: 
      containers: 
      - image: gitlab.lrz.de:5005/shortcut/tools/shortcut.lab/app_image
#      - image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        name: train-schedule
        ports:
          - containerPort: 8080
      imagePullSecrets: 
        - name: regcred
---
  
kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 30001
    nodePort: 30001
