apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: train-schedule
  name: train-schedule-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: train-schedule
  template: 
    metadata: 
      labels: 
        app: train-schedule
    spec: 
      containers:
      - image: gsimsek/train-schedule-kubernetes:latest
#      - image: "${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}"
        name: train-schedule
        ports:
          - containerPort: 8080
      imagePullSecrets: 
        - name: regsecret
---
  
apiVersion: v1
kind: Service
metadata:
  name: train-schedule
spec:
  selector:
    app: train-schedule
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
